### PR TITLE
Heterogeneous platforms generation proposal

### PR DESCRIPTION
**Pull request by RaMdsC**
- Multiple types of processors represented at core-grain
- Energy states per core
- Architecture for defining platforms based on Nodes, Networks and Processor types
- Naive support for memory specifications

Appreciate any kind of feedback :)

### CODE REVIEW

**Comment by mickours** [comment]
Thanks a lot for your contribution, I'm at SC18 right now but I will give you feedback next week.

**Review by mpoquet — CHANGES_REQUESTED** [review]
Thanks a lot!

- ``platform.xml`` is big, can you rebase your branch so it does not appear on the repo/use a tiny example instead?
- Can you increase the script description verbosity (or add a small README) to detail what kind of heterogeneity this platform generator allows to do? The word is used for many different things and I am afraid it could be confusing for future users otherwise.

**Review by mickours — APPROVED** [review]
Great job!  :+1:  Seems very cool for me :)

Just a remark, I see that you have put the memory as a zone property and I wonder how you intend to use this in the simulator?

You may be interested by the fact that we now have the notion of IO and storage in Batsim. It is modeled by a host with zero speed and with asymmetric links with the compute host and this property: `<prop id="role" value="storage"/>`.
Maybe the memory that you've add in the platform can be used as a storage this way.
Also, now that we have a cool platform generation tool, adding any kind of storage in the platform will be pretty easy, thanks for that! 

Have a look at the documentation here for more details and don't hesitate to drop me a mail if you have questions: https://batsim.readthedocs.io/en/latest/IO.html

Thanks again :)

**Comment by mickours** [comment]
Codacy suggests that you replace the xml library.

**Comment by mickours** [comment]
@mpoquet is it ok for you?

**Comment by mpoquet** [comment]
I think that's great :).

I would just add that it can be dangerous to model cores as hosts, as it removes the computations constraints usually present between cores. It can be perfectly fine if the scheduling is done at a finer grain in the decision process (e.g., to assign tasks to cores), but it can be misleading otherwise (with the traditional higher-level view of jobs in batsim workloads).

**Review by mpoquet — APPROVED** [review]

**Comment by mpoquet** [comment]
Merged in 08b1b07.

The merging process required some tricky rebases and editions, I hope I took all code related to this PR. Thanks again a lot @RaMdsC, please write your next pull request in a dedicated branch so merging is easier ;).

**Comment by RaMdsC** [comment]
Cool, will do sorry for the inconvenience, definitely need to improve my Git skills! :)

**Pull request closed without merging**
